info:
  contact:
    name: API Support
    url: https://developers.mercadolibre.com.ar/support
  description: This API Handle MELI Products
  license:
    name: Apache 2.0
    url: http://www.apache.org/license/LICENSE-2.0.html
  termsOfService: https://developers.mercadolibre.com.ar/es_as/terminos-y-condiciones
  title: MELI Bootcamp API
  version: "1.0"
paths: {}
swagger: "2.0"
